config/routes.rb
Rails.application.routes.draw do
  resources :accounts, except: %i[edit] do
    resources :statistics, only: %i[index create update]
    resources :transactions, only: %i[index create] do
      patch :cancel, :confirm, :ownerapprove
      post :exchange, on: :collection
    end
    resources :invites, only: %i[index create destroy update] do
      patch :confirm, :reject
    end
    resources :management, only: %i[index destroy]
    resources :co_users, only: %i[show update]
    # resources :rules, except: %i[show destroy]
    resources :exceeding_requests, only: %i[create update destroy]
  end

  devise_for :users,
             path: '',
             controllers: { registrations: 'registrations', confirmations: 'devise/confirmations' }

  root to: 'accounts#index'
end

app/controllers/co_users_controller.rb
class CoUsersController < ApplicationController
  def show
    account
    @transactions = Transaction.where(user_id: user_id, account_id: acc_id)
    @unconfirmed = Transaction.where(user_id: user_id, account_id: acc_id, status_from: 'in_approval')
    @rule = rule
  end

  def update
    rule.update!(co_user_params)
    limit.update!(reminder: co_user_params[:spending_limit])
    redirect_to :account_co_user, notice: 'Rules has been updated.'
  end

  private

  def account
    @account ||= Account.friendly.find(params[:account_id])
  end

  def user_id
    params[:id]
  end

  def acc_id
    account.id
  end

  def account_user
    AccountUser.find_by(user_id: user_id, account_id: acc_id)
  end

  def rule
    @rule ||= account_user.rule
  end

  def co_user_params
    params.fetch(:account_rule).permit(:spending_limit)
  end

  def limit
    account_user.limit
  end
end

app/views/co_users/show.html.haml
-if notice
  %div.alert.alert-success
    = notice
= link_to account_management_index_url, :class => "link_back" do
  %i.nc-icon.nc-minimal-left
  Back to List Co-Users

.row
  .col-md-10
    %h1 Edit co-user's rules
    .checkbox
      %input#checkbox1{:type => "checkbox"}/
      %label{:for => "checkbox1"}
        Edit
    .form-edit
      =render 'rules/edit_form'

.row
  .col-md-10
    %h3 Outgoing transactions
    -if @transactions
      %table.table-responsive
        %thead
          %tr
            %th To:
            %th Summ:
            %th Status:
            %th Created:
        %tbody
        - @transactions.each do |t|
          %tr
            %td= t.remote_account_iban
            %td= t.summ
            %td= t.status_from
            %td= t.created_at.to_formatted_s(:short)
    %h3 Unconfirmed transactions
    -if @unconfirmed
      %table.table-responsive
        %thead
          %tr
            %th To:
            %td Summ:
            %td From:
            %td Created:
        %tbody
        - @unconfirmed.each do |t|
          %tr
            %td= t.remote_account_iban
            %td= t.summ
            %td= t.user.name
            %td= t.created_at.to_formatted_s(:short)
            %td= link_to 'Confirm', account_transaction_ownerapprove_path(@account, t), :method => :patch, :class => 'btn btn-sm btn-outline-success'
            %td= link_to 'Cancel', account_transaction_cancel_path(@account, t), :method => :patch, :class => 'btn btn-sm btn-outline-danger'