config/routes.rb
Rails.application.routes.draw do
  resources :accounts, except: %i[edit] do
    resources :statistics, only: %i[index create update]
    resources :transactions, only: %i[index create] do
      patch :cancel, :confirm, :ownerapprove
      post :exchange, on: :collection
    end
    resources :invites, only: %i[index create destroy update] do
      patch :confirm, :reject
    end
    resources :management, only: %i[index destroy]
    resources :co_users, only: %i[show update]
    # resources :rules, except: %i[show destroy]
    resources :exceeding_requests, only: %i[create update destroy]
  end

  devise_for :users,
             path: '',
             controllers: { registrations: 'registrations', confirmations: 'devise/confirmations' }

  root to: 'accounts#index'
end

app/controllers/management_controller.rb
class ManagementController < ApplicationController
  include InvitesTracking

  before_action :account

  def index
    account
    account_manager = AccountManager.new(current_user, acc_id)
    @account_users = account_manager.manage
  end

  def destroy
    @role = account.account_users.find_by(user_id: current_user.id).role.name
    rule = AccountUser.find_by(id: params[:id]).rule
    @invite = Invite.find(rule.invite_id)
    track_closing
    @invite.close!
    rule.really_destroy!
    if @role == 'owner'
      redirect_to account_management_index_path, notice: 'Co-user was successfully deleted.'
    else
      redirect_to accounts_path, notice: "You left #{account.iban}"
    end
  end

  private

  def account
    @account = Account.friendly.find(params[:account_id])
  end

  def acc_id
    @account.id
  end
end

app/views/management/index.html.haml
-if notice
  %div.alert.alert-success
    = notice
= link_to account_url(@account), :class => "link_back" do
  %i.nc-icon.nc-minimal-left
  Back to Accounts Management

- role = @account_users[:role]
%h1 #{role}

.row
  .col-md-10
    %h3 Account users
    -if @account_users[:account_users]
      %table.table-responsive
        %thead
          %tr
          %th Email:
          %th Role type:
          %th Limit:
          %th Reminder:
        %tbody
        - @account_users[:account_users].each do |t|
          %tr
            %td= t.user.email
            %td= t.role.name
            %td= t.rule.spending_limit
            %td= t.limit.reminder
            %td= link_to 'Destroy', account_management_path(@account, t), method: :delete, class: 'btn btn-sm btn-outline-danger'
            -if role.eql? 'owner'
              %td= link_to 'Manage', account_co_user_path(@account, t.user), class: 'btn btn-sm btn-outline-primary'
  .col-md-2
    -if role.eql? 'owner'
      %div
        = link_to account_invites_path(@account), class: 'btn btn-outline-success btn-round btn-sm' do
          %i.nc-icon.nc-simple-add
          Invite co-user