config/routes.rb
Rails.application.routes.draw do
  resources :accounts, except: %i[edit] do
    resources :statistics, only: %i[index create update]
    resources :transactions, only: %i[index create] do
      patch :cancel, :confirm, :ownerapprove
      post :exchange, on: :collection
    end
    resources :invites, only: %i[index create destroy update] do
      patch :confirm, :reject
    end
    resources :management, only: %i[index destroy]
    resources :co_users, only: %i[show update]
    # resources :rules, except: %i[show destroy]
    resources :exceeding_requests, only: %i[create update destroy]
  end

  devise_for :users,
             path: '',
             controllers: { registrations: 'registrations', confirmations: 'devise/confirmations' }

  root to: 'accounts#index'
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  include TransactionsHistorian

  def index
    build_responce
  end

  def create
    transaction_creator = set_transaction
    if transaction_creator.check_creds
      transaction_creator.create_transaction
      redirect_to transaction_creator.account, notice: 'Transaction was successfully created.'
    else
      redirect_to account_path(params[:account_id]),
                  alert: 'Oops! Something wrong, try again later or contact administrator'
    end
  end

  def ownerapprove
    set_transaction.approve_from_owner
    redirect_to account_path(params[:account_id]), notice: 'Transaction was approved.'
  end

  def confirm
    redirection_router(set_transaction)
  end

  def cancel
    if set_transaction.cancel
      redirect_to account, notice: 'Transaction was cancelled.'
    else
      redirect_to account, notice: 'Transaction transaction already approved.'
    end
  end

  def exchange
    transaction_creator = set_exchange
    case transaction_creator.exchange
    when 'canceled'
      redirect_to exchange_account, notice: 'Not enough of money.'
    else
      redirect_to exchange_account, notice: 'Transaction completed successfully.'
    end
  end

  private

  def account
    account_path(params[:account_id])
  end

  def exchange_account
    account_path(Account.find_by(iban: params[:account]))
  end

  def set_transaction
    TransactionCreator.new(params, current_user)
  end

  def set_exchange
    params[:account] = Account.friendly.find(params[:account_id]).iban
    params[:account_id] = Account.find_by(iban: params[:refillable_account]).id
    TransactionCreator.new(params, current_user)
  end

  def redirection_router(transaction)
    account = account_path(params[:account_id])
    case transaction.confirm
    when 'canceled'
      redirect_to account, notice: 'Not enough money.'
    when 'in_approval'
      redirect_to account, notice: 'Exceeding the limit. Approve from owner requested.'
    else
      redirect_to account, notice: 'Transaction completed successfully.'
    end
  end
end

app/views/transactions/_form.html.haml
= form_for @transaction do |f|
  - if @transaction.errors.any?
    #error_explanation
      %h2= "#{pluralize(@transaction.errors.count, "error")} prohibited this transaction from being saved:"
      %ul
        - @transaction.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/transactions/edit.html.haml
%h1 Editing transaction

= render 'form'

= link_to 'Show', @transaction
\|
= link_to 'Back', transactions_path

app/views/transactions/index.html.haml
%h3 Transactions
-if @transactions
	%table
		%thead
			%tr
				%th User:
				%th From:
				%th To:
				%th Summ:
				%th Created:
		%tbody
		- @transactions.each do |t|
			%tr
				%td= t.user.email
				%td= t.account.iban
				%td= t.remote_account_iban
				%td= t.summ
				%td= t.created_at.to_formatted_s(:short)

.col-md-12
	.col.s8.input-field

		= text_field_tag :datepicker, nil, class: "datepicker"
	.col.s2.input-field
		= label_tag :title, 'Month'
		= text_field_tag :month
	.col.s2.input-field
		= label_tag :title, 'Day'
		= text_field_tag :day
	.col.s12.input-field
		= label_tag :title, 'Amount'
		= text_field_tag :summ
	= submit_tag 'Send'

app/views/transactions/new.html.haml
%h1 New transaction

= render 'form'

= link_to 'Back', transactions_path

app/views/transactions/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_transaction_path(@transaction)
\|
= link_to 'Back', transactions_path