config/routes.rb
Rails.application.routes.draw do
  resources :accounts, except: %i[edit] do
    resources :statistics, only: %i[index create update]
    resources :transactions, only: %i[index create] do
      patch :cancel, :confirm, :ownerapprove
      post :exchange, on: :collection
    end
    resources :invites, only: %i[index create destroy update] do
      patch :confirm, :reject
    end
    resources :management, only: %i[index destroy]
    resources :co_users, only: %i[show update]
    # resources :rules, except: %i[show destroy]
    resources :exceeding_requests, only: %i[create update destroy]
  end

  devise_for :users,
             path: '',
             controllers: { registrations: 'registrations', confirmations: 'devise/confirmations' }

  root to: 'accounts#index'
end

app/models/account.rb
class Account < ApplicationRecord
  acts_as_paranoid
  include Friendlyable
  has_many :transactions
  has_many :account_users, dependent: :destroy
  has_many :limits, through: :account_users
  has_many :roles, through: :account_users
  has_many :users, through: :account_users
  has_many :invites
  has_many :rules, through: :account_users
  has_many :exceeding_requests

  def valid_thru
    created_at + 3.days
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[show destroy]
  before_action :set_user_role, only: %i[show]
  attr_reader :accounts, :account, :income

  def index
    accounts_list
    invites_list
    @exceeding_request = ExceedingRequest.exceeding_requests_for(user)
  end

  def create
    iban = Ibandit::IBAN.new(country_code: 'BE',
                             account_number: Forgery('credit_card').number)
    account = Account.create!(iban: iban.iban,
                              balance: 1000)
    account.account_users.create(user: user, role_id: Role.find_by(name: 'owner').id)
    redirect_to account, notice: 'Account was successfully created.'
  end

  def show
    accounts_list
    outgoing_transactions_list
    incoming_transactions_list
  end

  def update
    Account.friendly.restore(params[:id], recursive: true)
    redirect_to accounts_url
  end

  def destroy
    account.destroy
    redirect_to accounts_url
  end

  private

  def set_user_role
    user.role_for(account)
  rescue RecordNotFound
    redirect_to accounts_path
  end

  def set_account
    @account ||= Account.friendly.find(params[:id])
  end

  def user
    @user ||= current_user
  end

  def accounts_list
    @accounts = user.accounts.to_a
  end

  def invites_list
    @invites ||= Invite.where(user_to_email: user.email, status: 'pending')
  end

  def outgoing_transactions_list
    @transactions = Transaction.where(user_id: user.id,
                                      account_id: account.id)
  end

  def incoming_transactions_list
    @income = Transaction.where(remote_account_iban: account.iban.to_s,
                                status_from: 'approved')
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def accs
    @accounts = current_user.accounts.without_deleted
  end
end

app/views/accounts/_co-user.html.haml
%table.table-responsive
  %thead
    %tr
      %th Iban
      %th Balance
      %th Date created
      %th Actions
  %tbody
  - @accounts.each do |account|
    -@rule_acc_co_user = account.account_users.with_deleted.find_by(user_id: current_user.id).role.name
    %tr
      -if @rule_acc_co_user == "co-user"
        -if account.deleted_at.nil?
          %td.iban #{account.iban}
          %td.balance #{account.account_users.find_by(user_id: current_user.id).limit.reminder}
          %td.date #{account.created_at.to_formatted_s(:short)}
          %td.actions
            = link_to 'Show', account, :class => 'btn btn-outline-primary btn-round btn-sm'
          / %td.actions
          /   = link_to 'Show', account, :class => 'btn btn-outline-info btn-round btn-sm'
          / -if account.deleted_at.nil?
          /   %td.date Freezed #{account.deleted_at.to_formatted_s(:short)}

app/views/accounts/_form.html.haml
= form_for @account do |f|
  - if @account.errors.any?
    #error_explanation
      %h2= "#{pluralize(@account.errors.count, "error")} prohibited this account from being saved:"
      %ul
        - @account.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/accounts/_modal.html.haml
%button.btn.btn-outline-primary.btn-round.btn-sm{ type: 'button', 'data-toggle': 'modal', 'data-target': '#myModal' }
  Replenish

%div.modal.fade#myModal{ tabindex: '-1', role: 'dialog', 'aria-labelledby': 'exampleModalLabel', 'aria-hidden': true }
  %div.modal-dialog{ role: 'document' }
    %div.modal-content
      %div.modal-header
        %h5.modal-title.text-center#exampleModalLabel Send money from account
        %button.close{ type: 'button', 'data-dismiss': 'modal', 'aria-label': 'Close' }
          %span{ 'aria-hidden': true } x

      %div.modal-body
        = form_tag exchange_account_transactions_path(active_account), method: :post do |f|
          - accounts = accs
          - (accounts-[active_account]).each do |account|
            %div.row
              %div.col-md-6
                %input{ type: 'radio', name: 'refillable_account', value: account.iban }
                  = account.iban
                  |
                  = account.balance
          %div.row
            %div.col-md-6
              %div.form-group
                %input.form-control{ placeholder: 'Amount', name: 'summ' }
          = submit_tag 'Send', class: 'btn btn-outline-success btn-round btn-sm'

app/views/accounts/_owner.html.haml
%table.table-responsive
  %thead
    %tr
      %th Iban
      %th Balance
      %th Date created
      %th Actions
  %tbody
    - @accounts.each do |account|
      -@rule_acc = account.account_users.with_deleted.find_by(user_id: current_user.id).role.name
      %tr
        -if @rule_acc == "owner"
          %td.iban #{account.iban}
          %td.balance #{account.balance}
          %td.date #{account.created_at.to_formatted_s(:short)}
          -unless account.deleted_at
            %td.actions
              = link_to 'Show', account, :class => 'btn btn-outline-primary btn-round btn-sm'
              = link_to 'Delete', account, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-outline-danger btn-round btn-sm'
          -if account.deleted_at?
            %td.actions
              = link_to 'Restore', account, :method => :patch, :class => 'btn btn-sm btn-outline-warning'
            %td.date Frozen #{account.deleted_at.to_formatted_s(:short)}

app/views/accounts/_tabs.html.haml
- @tab_owner = 0
- @tab_cu = 0
- @accounts.each do |account|
  -@rule_acc = account.account_users.with_deleted.find_by(user_id: current_user.id).role.name
  -if @rule_acc == "owner"
    - @tab_owner = 1
  -if @rule_acc == "co-user"
    - @tab_cu = 2
%ul.nav.nav-tabs{:role => "tablist"}
  -if @tab_owner == 1
    %li.nav-item
      %a.nav-link.active{"data-toggle" => "tab", :href => "#owner-2", :role => "tab"} Owner
  -if @tab_owner == 1 && @tab_cu == 2  
    %li.nav-item
      %a.nav-link{"data-toggle" => "tab", :href => "#co-user-2", :role => "tab"} Co-User
  -if @tab_owner == 0 && @tab_cu == 2
    %li.nav-item
      %a.nav-link.active{"data-toggle" => "tab", :href => "#co-user-2", :role => "tab"} Co-User
 

app/views/accounts/edit.html.haml
%h1 Editing account

= render 'form'

= link_to 'Show', @account
\|
= link_to 'Back', accounts_path

app/views/accounts/index.html.haml
-if notice
  %div.alert.alert-success
    = notice
-if alert
  %div.alert.alert-danger
    =alert
.row
  .col-md-10
    .nav-tabs-navigation
      .nav-tabs-wrapper
        = render :partial => "./accounts/tabs"            
    / Tab panes
    .tab-content.text-center
      -if @tab_owner == 1
        #owner-2.tab-pane.active{:role => "tabpanel"}
          = render :partial => "./accounts/owner"
      -if @tab_owner == 1 && @tab_cu == 2
        #co-user-2.tab-pane{:role => "tabpanel"}
          = render :partial => "./accounts/co-user"      
      -if @tab_owner == 0 && @tab_cu == 2
        #co-user-2.tab-pane.active{:role => "tabpanel"}
        = render :partial => "./accounts/co-user"
      -if @tab_owner == 0 && @tab_cu == 0
        %h5 You don't have any accounts

  .col-md-2
    = form_for new_account_path do |f|
      = f.submit 'New Account', :class => 'btn btn-outline-success btn-round'
    = link_to 'Change User info', edit_user_registration_path, :class => 'btn btn-sm btn-outline-primary waves-effect'

%div
-unless @invites.to_a.empty?
  %h3 Invitations
  %table.table-responsive
    %thead
      %tr
        %th From user_id:
        %th iban:
        %th Accept:
        %th Reject:
    %tbody
    - @invites.each do |invite|
      %tr
        %td= invite.user_from_id
        %td= invite.account.iban
        %td= link_to 'Submit', account_invite_confirm_path(invite.account_id, invite.id), method: :patch, class: 'btn btn-sm btn-outline-success'
        %td= link_to 'Reject', account_invite_reject_path(invite.account_id, invite.id), method: :patch, class: 'btn btn-sm btn-outline-danger'
%div

-unless @exceeding_request.to_a.empty?
  %h3 Exceeding requests
  %table
    %thead
      %tr
        %th Account
        %th User
        %th Amount
        %th Actions
    %tbody
    - @exceeding_request.each do |request|
      %tr
        %td= request.account.iban
        %td= request.user.name
        %td= request.amount
        %td
          = link_to 'Accept invite', account_exceeding_request_path(request.account.id, request.id, exceeding_request: { status: true }), method: :patch, class: 'btn btn-sm btn-outline-primary'
          = link_to 'Reject', account_exceeding_request_path(request.account.id, request.id, exceeding_request: { status: false }), method: :patch, class: 'btn btn-sm btn-outline-danger'

app/views/accounts/new.html.haml
%h1 New account

%input{:type=>"text", :name=>"account-new"}
= render 'form'

= link_to 'Back', accounts_path

app/views/accounts/show.html.haml
-if notice
  %div.alert.alert-success
    = notice
= link_to accounts_path, :class => "waves-effect waves-light link_back" do
  %i.nc-icon.nc-minimal-left
  Back to Accounts Page

.row
  .col-md-10.iban-info
    .row
      .col-md-8
        %h5 #{@account.iban}
        %h5= 'Valid THRU: ' + @account.valid_thru.strftime('%m/%d')
        %h5= @account.account_users.find_by(user_id: current_user.id).role.name
      .col-md-4
        -if can? :check_account_balance, @account
          %h5 Balance: #{@account.balance}
        -elsif can? :check_own_remainder, @account
          %h5 Balance: #{@account.account_users.find_by(user_id: current_user.id).limit.reminder}
  .col-md-2.btn-acc
    .stat
      = link_to 'Statistics', account_statistics_path(@account), :class => 'btn btn-outline-primary btn-round btn-sm'
    .manage
      = link_to 'Management', account_management_index_path(@account), :class => 'btn btn-outline-primary btn-round btn-sm'
    -if can? :can_replenish, @account
      .replenishment
        = render partial: 'modal', object: @account, as: :active_account

-if can? :do_exceeding_request, @account
  =form_tag account_exceeding_requests_url(@account), method: :post, action: :create do
    =text_field_tag 'exceeding_request[amount]'
    =submit_tag 'Request exceeding limit'
.row
  .col-md-10
    .nav-tabs-navigation
      .nav-tabs-wrapper
        %ul.nav.nav-tabs{:role => "tablist"}
          %li.nav-item
            %a.nav-link.active{"data-toggle" => "tab", :href => "#out_trans", :role => "tab"} Outgoing transactions
          -if can? :can_income, Transaction
            %li.nav-item
              %a.nav-link{"data-toggle" => "tab", :href => "#inc_trans", :role => "tab"} Incoming transactions
    / Tab panes
    .tab-content.text-center
      #out_trans.tab-pane.active{:role => "tabpanel"}
        -if @transactions
          %table.table-responsive
            %thead
              %tr
                %th To:
                %th Summ:
                %th Created:
                %th Status:
            %tbody
            - @transactions.each do |t|
              %tr
              %td= t.remote_account_iban
              %td= t.summ
              %td= t.created_at.to_formatted_s(:short)
              %td= t.status_from
              -if t.pending?
                %td.actions
                  = link_to 'Confirm', account_transaction_confirm_path(@account, t), :method => :patch, :class => 'btn btn-sm btn-outline-success btn-round'
                  = link_to 'Cancel', account_transaction_cancel_path(@account, t), :method => :patch, :class => 'btn btn-sm btn-outline-danger'
              -if t.in_approval?
                %td.actions
                  = link_to 'Cancel', account_transaction_cancel_path(@account, t), :method => :patch, :class => 'btn btn-sm btn-outline-danger'
      #inc_trans.tab-pane{:role => "tabpanel"}
        -if can? :can_income, @income.last
          %table.table-responsive
            %thead
              %tr
                %th From:
                %th Summ:
                %th Created:
            %tbody
            - @income.each do |t|
              %tr
                %td= t.account.iban
                %td= t.summ
                %td= t.created_at.to_formatted_s(:short)

/= button_tag 'New Transaction', :id => 'new-trans', :class => 'btn btn-outline-success btn-round btn-sm'
.col-md-10
  = form_tag account_transactions_path(@account), method: :post do
    .row
      .col-md-8.form-group
        = text_field_tag :account, nil, class: 'form-control', placeholder: 'Account Iban'
      .col-md-2.form-group
        = text_field_tag :month, nil, class: 'form-control', placeholder: 'Month'
      .col-md-2.form-group
        = text_field_tag :day, nil, class: 'form-control', placeholder: 'Day'
      .col-md-12.form-group
        = text_field_tag :summ, nil, class: 'form-control', placeholder: 'Amount'
      .col-md-12.form-group
        = submit_tag 'Send', :class => 'btn btn-outline-success btn-round btn-sm'


/ %input{:list => "colors", :type => "text", :value => ""}/
/ %datalist#colors
/   - @accounts.each do |account|
/     %option{:name => "user_id", :value => account.iban}